name: "execute"

on:
  workflow_dispatch:

jobs:
  execute:
    name: Post
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm isntall

      - name: Build
        run: npm run build

      - name: Start
        run: npm start

        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

