name: "execute"

on:
  workflow_dispatch:

jobs:
  execute:
    name: Post
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm isntall

      - name: Build
        run: npm run build

      - name: Run my action
        uses: ./.github/actions/execution
